[[mgr.prepend_keymap]]
on = "q"
run = "quit --no-cwd-file"
desc = "Quit without changing directory"

[[mgr.prepend_keymap]]
on = "<C-a>"
run = "quit --no-cwd-file"
desc = "Quit without changing directory"

[[mgr.prepend_keymap]]
on = "!"
run = "quit"
desc = "Quit and change directory"
