
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'

format = """\
$all
$os $directory$character"""

command_timeout = 2000

# ==========================
# Catppuccin Mocha Palette
# https://github.com/catppuccin/starship/tree/main
# ==========================
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# ==========================
# OS Symbols
# ==========================
[os.symbols]
Kali = "  "
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

# ==========================
# Modules
# ==========================

[os]
disabled = false
format = "[$symbol]($style)"
style = "fg:sky"

[directory]
format = "[ $path]($style)"
style = "bold fg:blue"
truncation_length = 0
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = "🌱"
style = "fg:mauve"
format = '\[[$symbol$branch]($style)\]'

[git_status]
style = "fg:subtext1"
format = '${all_status}${ahead_behind}'
conflicted = '\[[🏳](fg:red)\] '
ahead = '\[[${count} to push👆](fg:green)\] '
behind = '\[[${count} to pull👇](fg:red)\] '
diverged = '\[[diverged😲](fg:red)\] '
up_to_date = '\[[up to date ✅](fg:green)\] '
untracked = '\[[$count untracked🤷](fg:yellow)\] '
stashed = '\[[$count stashed🧺](fg:yellow)\] '
modified = '\[[$count modified📝](fg:yellow)\] '
staged = '\[[$count staged🔒](fg:green)\] '
renamed = '\[[$count renamed🚩](fg:yellow)\] '
deleted = '\[[$count deleted🗑️](fg:red)\] '

[cmd_duration]
format = ' \[[⏱ $duration]($style)\]'
style = "fg:subtext0"
disabled = true

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[>](bold fg:green)'
error_symbol = '[>](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
